# Labels: define labels for Issues and Pull Requests
labels:
  - name: feature2
    color: 336699
    description: Cool stuff
  - name: first-timers-only
    # include the old name to rename and existing label
    oldname: Help Wanted
